### ISSUE TITLE
Error while running an app

### ISSUE THREAD

**Issue by mumarse** [Shopify/shopify-app-template-ruby#121]
when i make a new app using this template app (i.e. https://github.com/Shopify/shopify-app-template-ruby) is not running and get the following error

npm init @shopify/app@latest -- --template=ruby
cd web
bundle install
bin/rails app:template LOCATION=./template.rb
cd ..
npm run dev

all is working fine but when i run npm run dev i get the following error
Error:
── external error ──────────────────────────────

Error coming from `bin/rails server`

Command failed with exit code 1: bin/rails      
server
C:/Users/Buzz Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:332:in `raise_not_found!': Could not find gem
'shopify_app (~> 21.9)' in locally installed    
gems. (Bundler::GemNotFound)
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:392:in `block in    
prepare_dependencies'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:377:in `each'       
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:377:in `map'        
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:377:in
`prepare_dependencies'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:61:in `setup_solver'        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:28:in `start'       
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:626:in
`start_resolution'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:311:in `resolve'  
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:579:in
`materialize'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:203:in `specs'    
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:270:in `specs_for'        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:18:in `setup'        
        from C:/Users/Buzz Tech/.local/share/gem/ruby/3.
2.0/gems/bundler-2.5.6/lib/bundler.rb:162:in    
`setup'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/setup.rb:26:in `block in <top   
(required)>'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/ui/shell.rb:159:in `with_level' 
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/ui/shell.rb:111:in `silence'    
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/setup.rb:26:in `<top
(required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/ruby
gems/core_ext/kernel_require.rb>:85:in `require'        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/ruby
gems/core_ext/kernel_require.rb>:85:in `require'        from C:/Users/Buzz Tech/Desktop/New folder/conso
lidated-trade-app/web/config/boot.rb:6:in `<top 
(required)>'
        from C:/Users/Buzz Tech/Desktop/New     
folder/consolidated-trade-app/web/bin/rails:3:in `require_relative'
        from C:/Users/Buzz Tech/Desktop/New     
folder/consolidated-trade-app/web/bin/rails:3:in `<main>'

![Screenshot 2024-02-19 010600](https://github.com/Shopify/shopify-app-template-ruby/assets/61001668/7ed100f0-8dbc-4715-b6d5-b1976a9d69d0)

![Screenshot 2024-02-19 010641](https://github.com/Shopify/shopify-app-template-ruby/assets/61001668/9bd7390b-f932-4151-95ae-e8b156a78473)

![Screenshot 2024-02-19 010705](https://github.com/Shopify/shopify-app-template-ruby/assets/61001668/35addcce-256d-4844-b545-717d9a35c3aa)
![Screenshot 2024-02-19 010732](https://github.com/Shopify/shopify-app-template-ruby/assets/61001668/d0b474c9-19da-42a2-8249-b4c09f8b09fe)

- shopify_api version: 
- shopify_app version: 3.56.1
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]
- Operating system:  wundows

when i run npm run dev after creating an app get the following error istead of running an app
── external error ──────────────────────────────

Error coming from `bin/rails server`

Command failed with exit code 1: bin/rails      
server
C:/Users/Buzz Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:332:in `raise_not_found!': Could not find gem
'shopify_app (~> 21.9)' in locally installed    
gems. (Bundler::GemNotFound)
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:392:in `block in    
prepare_dependencies'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:377:in `each'       
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:377:in `map'        
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:377:in
`prepare_dependencies'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:61:in `setup_solver'        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/resolver.rb:28:in `start'       
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:626:in
`start_resolution'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:311:in `resolve'  
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:579:in
`materialize'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:203:in `specs'    
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/definition.rb:270:in `specs_for'        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:18:in `setup'        
        from C:/Users/Buzz Tech/.local/share/gem/ruby/3.
2.0/gems/bundler-2.5.6/lib/bundler.rb:162:in    
`setup'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/setup.rb:26:in `block in <top   
(required)>'
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/ui/shell.rb:159:in `with_level' 
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/ui/shell.rb:111:in `silence'    
        from C:/Users/Buzz
Tech/.local/share/gem/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/setup.rb:26:in `<top
(required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/ruby
gems/core_ext/kernel_require.rb>:85:in `require'        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/ruby
gems/core_ext/kernel_require.rb>:85:in `require'        from C:/Users/Buzz Tech/Desktop/New folder/conso
lidated-trade-app/web/config/boot.rb:6:in `<top 
(required)>'
        from C:/Users/Buzz Tech/Desktop/New     
folder/consolidated-trade-app/web/bin/rails:3:in `require_relative'
        from C:/Users/Buzz Tech/Desktop/New     
folder/consolidated-trade-app/web/bin/rails:3:in `<main>'

**Comment by mumarse** [comment]
yes i have set up the app by using the instructions in the README but got error when run the app details of error are above

**Comment by mumarse** [comment]
I know that the error comes when running bundle install inside the web folder ? The reason to answer this query is that how to solve the error ?

Error:
── external error ──────────────────────────────

Error coming from bin/rails server

Command failed with exit code 1: bin/rails
server
